# .golangci.yml

version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - unparam
    - dupl
    - ineffassign
    - misspell
    - bodyclose
    - cyclop
    - dupword
    - revive
    - goconst
    - gocritic
    - nestif
    - whitespace
    - varnamelen
    - prealloc

run:
  tests: true


