// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock

import (
	context "context"

	repository "github.com/Ranik23/url-shortener/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// TxManager is an autogenerated mock type for the TxManager type
type TxManager struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0, _a1
func (_m *TxManager) Do(_a0 context.Context, _a1 func(context.Context) error) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DoWithSettings provides a mock function with given fields: _a0, _a1, _a2
func (_m *TxManager) DoWithSettings(_a0 context.Context, _a1 repository.Settings, _a2 func(context.Context) error) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DoWithSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Settings, func(context.Context) error) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxManager creates a new instance of TxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxManager {
	mock := &TxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
